StartupEvents.registry('block', event => {
    event.create("compressed_netherrack")
    .displayName("Compressed Netherrack")
    .soundType('netherrack')
    .hardness(4)
    .resistance(1)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_wooden_tool')

    event.create("compressed_basalt")
    .displayName("Compressed Basalt")
    .soundType('basalt')
    .hardness(4)
    .resistance(1)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_wooden_tool')

    event.create("compressed_diamond_block")
    .displayName("Compressed Diamond Block")
    .hardness(6)
    .resistance(1)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')

    event.create("compressed_emerald_block")
    .displayName("Compressed Emerald Block")
    .hardness(6)
    .resistance(1)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')

    event.create("compressed_netherite_block")
    .displayName("Compressed Netherite Block")
    .soundType('netherite_block')
    .hardness(10)
    .resistance(100)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_diamond_tool')

    event.create("brust_alloy_block")
    .displayName("Brust Alloy Block")
    .soundType('netherite_block')
    .hardness(15)
    .resistance(100)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_diamond_tool')

    event.create("adamantium_ore")
    .displayName("Adamantium Ore")
    .stoneSoundType()
    .hardness(20)
    .resistance(100)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:incorrect_for_wooden_tool')
    .tagBlock('minecraft:incorrect_for_stone_tool')
    .tagBlock('minecraft:incorrect_for_iron_tool')
    .tagBlock('minecraft:incorrect_for_gold_tool')
    .tagBlock('minecraft:incorrect_for_diamond_tool')

    event.create("mithril_ore")
    .displayName("Mithril Ore")
    .stoneSoundType()
    .hardness(25)
    .resistance(100)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:incorrect_for_wooden_tool')
    .tagBlock('minecraft:incorrect_for_stone_tool')
    .tagBlock('minecraft:incorrect_for_iron_tool')
    .tagBlock('minecraft:incorrect_for_gold_tool')
    .tagBlock('minecraft:incorrect_for_diamond_tool')

    event.create("adamantium_block")
    .displayName("Adamantium Block")
    .soundType('netherite_block')
    .hardness(25)
    .resistance(100)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:incorrect_for_wooden_tool')
    .tagBlock('minecraft:incorrect_for_stone_tool')
    .tagBlock('minecraft:incorrect_for_iron_tool')
    .tagBlock('minecraft:incorrect_for_gold_tool')
    .tagBlock('minecraft:incorrect_for_diamond_tool')

    event.create("mithril_block")
    .displayName("Mithril Block")
    .soundType('netherite_block')
    .hardness(25)
    .resistance(100)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:incorrect_for_wooden_tool')
    .tagBlock('minecraft:incorrect_for_stone_tool')
    .tagBlock('minecraft:incorrect_for_iron_tool')
    .tagBlock('minecraft:incorrect_for_gold_tool')
    .tagBlock('minecraft:incorrect_for_diamond_tool')

    event.create("raw_adamantium_block")
    .displayName("Raw Adamantium Block")
    .hardness(25)
    .resistance(100)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:incorrect_for_wooden_tool')
    .tagBlock('minecraft:incorrect_for_stone_tool')
    .tagBlock('minecraft:incorrect_for_iron_tool')
    .tagBlock('minecraft:incorrect_for_gold_tool')
    .tagBlock('minecraft:incorrect_for_diamond_tool')


    event.create("raw_mithril_block")
    .displayName("Raw Mithril Block")
    .hardness(25)
    .resistance(100)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:incorrect_for_wooden_tool')
    .tagBlock('minecraft:incorrect_for_stone_tool')
    .tagBlock('minecraft:incorrect_for_iron_tool')
    .tagBlock('minecraft:incorrect_for_gold_tool')
    .tagBlock('minecraft:incorrect_for_diamond_tool')


    event.create("randomize_ore")
    .displayName("Randomize Block")
    .stoneSoundType()
    .hardness(10)
    .resistance(100)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')

    event.create("immortal_alloy_block")
    .displayName("Immortal Alloy Block")
    .soundType('netherite_block')
    .hardness(30)
    .resistance(100)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:incorrect_for_wooden_tool')
    .tagBlock('minecraft:incorrect_for_stone_tool')
    .tagBlock('minecraft:incorrect_for_iron_tool')
    .tagBlock('minecraft:incorrect_for_gold_tool')
    .tagBlock('minecraft:incorrect_for_diamond_tool')
})


StartupEvents.registry('fluid', event => {
    const molten_immortal = event
    .create('molten_immortal')
    .displayName('Liquid Immortal')
    //.stillTexture('kubejs:block/strawberry_still')
    //.flowingTexture('kubejs:block/strawberry_flow')
    
    molten_immortal.bucketItem
})