Platform.mods.kubejs.name = 'FarSight.T.N.E.Expeded'
StartupEvents.registry('item', event => {
    event.create('glass_crest')
    .displayName('Glass Crest')
    event.create('night_crest')
    .displayName('Night Crest')
    event.create("glass_crest_core")
    .displayName("Glass Crest Core")
    event.create("upgrade_core")
    .displayName("Upgrade Core")
    event.create("forged_upgrade_smithing_template").
    displayName("Forged Upgrade Smithing Template")
    event.create("heavy_upgrade_smithing_template")
    .displayName("Heavy Upgrade Smithing Template")
    event.create("ocean_upgrade_smithing_template")
    .displayName("Ocean Upgrade Smithing Template")
    event.create("crest_upgrade_smithing_template")
    .displayName("Crest Upgrade Smithing Template")
    event.create("three_in_one_upgrade_smithing_template")
    .displayName("Three In One Upgrade Smithing Template")
    event.create("trident_head")
    .displayName("Trident Head")
    event.create("mirror_core")
    .displayName("Mirror Core")
    event.create("fork_core")
    .displayName("Fork_Core")
    event.create("brust_alloy")
    .displayName("Brust Alloy")
    event.create("high_performance_explosive")
    .displayName("High-performance explosive")
    event.create('echo_shadow',"hoe")
    .displayName('Echo Shadow')
    .tier('netherite')
    event.create('malachite_reatsword','sword')
    .displayName('Malachite Reatsword')
    .tier('netherite')
    event.create('dreamflayer','sword')
    .displayName('DreamFlayer')
    .tier('netherite')
    event.create('draconic_twinsword','sword')
    .displayName('Draconic Twinsword')
    .tier('netherite')
    event.create('endness','sword')
    .displayName('Endness')
    .tier('netherite')
    event.create('nightmare','axe')
    .displayName('NightMare')
    .tier('netherite')
    event.create('soul_severing_pick','pickaxe')
    .displayName('Soul Severing Pick')
    .tier('netherite')
    event.create('shovel_leak','shovel')
    .displayName('Empty')
    .tier('netherite')
})

StartupEvents.registry('block', event => {
    event.create("compressed_netherrack")
    .displayName("Compressed Netherrack")
    .soundType('netherrack')
    .hardness(4)
    .resistance(1)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_wooden_tool')
    event.create("compressed_diamond_block")
    .displayName("Compressed Diamond Block")
    .hardness(6)
    .resistance(1)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    event.create("compressed_emerald_block")
    .displayName("Compressed Emerald Block")
    .hardness(6)
    .resistance(1)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    event.create("compressed_netherite_block")
    .displayName("Compressed Netherite Block")
    .soundType('netherite_block')
    .hardness(10)
    .resistance(100)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_diamond_tool')
    event.create("brust_alloy_block")
    .displayName("Brust Alloy Block")
    .soundType('netherite_block')
    .hardness(10)
    .resistance(100)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_diamond_tool')
})
ItemEvents.toolTierRegistry(event => {
    event.add('brust_alloy', tier => {
      tier.uses = 250
      tier.speed = 6
      tier.attackDamageBonus = 2
      tier.enchantmentValue = 14
      tier.repairIngredient = '#forge:ingots/iron'
    })
  })