Platform.mods.kubejs.name = 'Farsight.T.N.E. Title'
StartupEvents.registry('item', event => {
    event.create('glass_crest').displayName('月琉璃')
    event.create('night_crest').displayName('夜琉璃')
    event.create("glass_crest_core").displayName("月琉璃核心")
    event.create("upgrade_core").displayName("升级核心")
    event.create("forged_upgrade_smithing_template").displayName("重铸升级锻造模板")
    event.create("heavy_upgrade_smithing_template").displayName("重型升级锻造模板")
    event.create("ocean_upgrade_smithing_template").displayName("海洋升级锻造模板")
    event.create("crest_upgrade_smithing_template").displayName("琉璃升级锻造模板")
    event.create("three_in_one_upgrade_smithing_template").displayName("三合一升级锻造模板")
    event.create("trident_head").displayName("三叉戟头部")
    event.create("mirror_core").displayName("棱镜核心")
    event.create("fork_core").displayName("激荡核心")
    event.create('echo_shadow',"hoe").displayName('回溯影镰-占位符').tier('netherite')
    event.create('malachite_reatsword','sword').displayName('孔雀石巨剑-占位符').tier('netherite')
    event.create('dreamflayer','sword').displayName('离梦利刃-占位符').tier('netherite')
    event.create('draconic_twinsword','sword').displayName('龙之双剑-占位符').tier('netherite')
    event.create('endness','sword').displayName('终焉-占位符').tier('netherite')
    event.create('nightmare','axe').displayName('梦魇-占位符').tier('netherite')
    event.create('soul_severing_pick','pickaxe').displayName('离魂镐-占位符').tier('netherite')
    event.create('shovel_leak','shovel').displayName('占位符').tier('netherite')
})